---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "hello-lagom-scala-openshift-smoketests-service-v1-7-snapshot"
  labels:
    appName: "hello-lagom-scala-openshift-smoketests-service"
    appNameVersion: "hello-lagom-scala-openshift-smoketests-service-v1-7-snapshot"
spec:
  replicas: 3
  selector:
    matchLabels:
      appNameVersion: "hello-lagom-scala-openshift-smoketests-service-v1-7-snapshot"
  template:
    metadata:
      labels:
        appName: "hello-lagom-scala-openshift-smoketests-service"
        appNameVersion: "hello-lagom-scala-openshift-smoketests-service-v1-7-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: "hello-lagom-scala-openshift-smoketests-service"
          image: "hello-lagom:1.0-SNAPSHOT"
          imagePullPolicy: Always
          env:
            - name: "JAVA_OPTS"
              value: "-Dconfig.resource=application-prod.conf -Dplay.server.pidfile.path=/dev/null"
            - name: "TRANSPORT_HTTP_BIND_ADDRESS"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "DEPLOYMENT_SERVICE_NAME"
              value: "hello-lagom-scala-openshift-smoketests-service"
          ports:
            # application
            - name: http
              containerPort: 9000
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
          # The readiness and liveness probes settings need to be tuned depending on the
          # capacity of your cluster and the resources settings (below)
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            initialDelaySeconds: 90
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            initialDelaySeconds: 60
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 1
              memory: 512Mi
          command:
            - "/opt/docker/bin/hello-impl"
      volumes: []